import crypto from 'crypto'

export async function myHead() {
    return Promise.resolve({
        title: 'Create Next App',
        description: 'Generated by create next app' + crypto.randomBytes(4).toString('hex'),
    }) 
}